<?php
// 代码生成时间: 2025-09-04 23:51:12
class ExcelGenerator {
    
    /**
     * Generates an Excel file with the provided data.
     * 
     * @param array $data Data to be written in the Excel file.
     * @param string $filename The name of the file to be generated.
     * @throws Exception If there is an error during file generation.
     */
    public function generateExcelFile($data, $filename) {
        try {
            // Create a new PHPExcel object
            $objPHPExcel = new PHPExcel();
            
            // Set properties of the spreadsheet
            $objPHPExcel->getProperties()
                ->setCreator("Your Name")
                ->setTitle("Excel File Generated by PHP");

            // Set active sheet index to the first sheet, so Excel opens this as the first sheet
            $objPHPExcel->setActiveSheetIndex(0);
            
            // Add data to the active sheet
            $rowCount = 1;
            foreach ($data as $row => $value) {
                $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(1, $rowCount, $value['header']);
                $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(2, $rowCount, $value['body']);
                $rowCount++;
            }

            // Set the title of the active sheet
            $objPHPExcel->getActiveSheet()->setTitle("Generated Data");

            // Create awriter to write the Excel file
            $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
            
            // Save the file to the specified path
            $objWriter->save($filename);

            echo "Excel file generated successfully.
";
        } catch (Exception $e) {
            // Handle any exceptions that may occur during the file generation process
            echo "An error occurred: " . $e->getMessage() . "
";
        }
    }
}

// Usage example
/**
 * Assuming you have an array of data to be written to the Excel file.
 * Each element in the array contains 'header' and 'body' fields.
 */
$data = [
    ['header' => 'Header 1', 'body' => 'Body 1'],
    ['header' => 'Header 2', 'body' => 'Body 2'],
    // ... more data rows
];

$excelGenerator = new ExcelGenerator();
$excelGenerator->generateExcelFile($data, 'generated_excel_file.xlsx');
